version: '3.9'
services:
  servicestack-docs-search:
    image: ghcr.io/servicestack/docs-search:latest
    network_mode: bridge
    ports:
      - "8108"
    environment:
      VIRTUAL_HOST: "${HOST_DOMAIN}"
      LETSENCRYPT_HOST: "${HOST_DOMAIN}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
      TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
    command:
      - "--data-dir"
      - "/data"
      - "--api-key"
      - "${TYPESENSE_API_KEY}"
      - "--enable-cors"

